name: Build e MSI do LigacoesPorHora

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Instalar dependências
        run: pip install pyinstaller pandas matplotlib

      - name: Gerar EXE com PyInstaller
        run: |
          pyinstaller ligacoes.py --onefile --noconsole --icon=icone.ico --name LigacoesPorHora

      - name: Baixar Inno Setup
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://jrsoftware.org/download.php/is.exe -OutFile is.exe
          Start-Process .\is.exe -ArgumentList '/VERYSILENT', '/SUPPRESSMSGBOXES', '/NORESTART', '/DIR="C:\InnoSetup"' -Wait

      - name: Criar script do Inno Setup
        run: |
          echo [Setup] > installer.iss
          echo AppName=LigacoesPorHora >> installer.iss
          echo AppVersion=1.0 >> installer.iss
          echo DefaultDirName={pf}\LigacoesPorHora >> installer.iss
          echo DefaultGroupName=LigacoesPorHora >> installer.iss
          echo UninstallDisplayIcon={app}\LigacoesPorHora.exe >> installer.iss
          echo OutputDir=. >> installer.iss
          echo OutputBaseFilename=LigacoesPorHora_Installer >> installer.iss
          echo SetupIconFile=icone.ico >> installer.iss
          echo [Files] >> installer.iss
          echo Source: "dist\LigacoesPorHora.exe"; DestDir: "{app}"; Flags: ignoreversion >> installer.iss
          echo [Icons] >> installer.iss
          echo Name: "{group}\LigacoesPorHora"; Filename: "{app}\LigacoesPorHora.exe" >> installer.iss
          echo Name: "{commondesktop}\LigacoesPorHora"; Filename: "{app}\LigacoesPorHora.exe"; Tasks: desktopicon >> installer.iss
          echo [Tasks] >> installer.iss
          echo Name: desktopicon; Description: "Criar atalho na área de trabalho"; GroupDescription: "Opções adicionais:" >> installer.iss

      - name: Gerar Instalador MSI
        run: |
          "C:\InnoSetup\ISCC.exe" installer.iss

      - name: Upload do .EXE
        uses: actions/upload-artifact@v4
        with:
          name: LigacoesPorHora-EXE
          path: dist/LigacoesPorHora.exe

      - name: Upload do Instalador
        uses: actions/upload-artifact@v4
        with:
          name: LigacoesPorHora-Installer
          path: LigacoesPorHora_Installer.exe

