name: Build EXE for Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests matplotlib

      - name: Compilar EXE com PyInstaller
        run: pyinstaller --noconsole --onefile ligacoes.py

      - name: Publicar artefato
        uses: actions/upload-artifact@v3
        with:
          name: ligacoes-exe
          path: dist/ligacoes.exe

